feat: setup initial DA module structure
Finschia/finschia-sdk pull request #993
Opened 2023-05-02 11:25 UTC by tkxkd0159

## Description

closes: #XXXX

## Motivation and context

## How has this been tested?

## Screenshots (if appropriate):

## Checklist:

- [ ] I followed the [contributing guidelines](https://github.com/Finschia/finschia-sdk/blob/main/CONTRIBUTING.md) and [code of conduct](https://github.com/Finschia/finschia-sdk/blob/main/CODE_OF_CONDUCT.md).
- [ ] I have added a relevant changelog to `CHANGELOG.md`
- [ ] I have added tests to cover my changes.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated API documentation `client/docs/swagger-ui/swagger.yaml`

2023-05-02 11:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Finschia/finschia-sdk?pullRequest=993) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Finschia/finschia-sdk?pullRequest=993) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: tkxkd0159<br/>:x: Jaeseung Lee<br/><hr/>**Jaeseung Lee** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Finschia/finschia-sdk?pullRequest=993) it.</sub>

2023-05-17 07:39 UTC, torao commented on x/or/da/keeper/cc.go
> +func (k Keeper) appendSequencerBatch() {
It's better to leave some comment on the lint check failure, as similar check failures may be reported in another PR later on.

2023-05-17 09:37 UTC, torao approved these changes

2023-05-18 03:27 UTC, ulbqb requested changes

2023-05-18 03:27 UTC, ulbqb commented on proto/finschia/or/da/v1/da.proto
> +}
```suggestion
}

```

2023-05-18 03:27 UTC, ulbqb commented on proto/finschia/or/da/v1/genesis.proto
> +}
```suggestion
}

```

2023-05-18 03:27 UTC, ulbqb commented on proto/finschia/or/da/v1/query.proto
> +    option (google.api.http).get = "/checkers/da/params";
```suggestion
    option (google.api.http).get = "/finschia/or/da/v1/params";
```

2023-05-18 03:27 UTC, ulbqb commented on proto/finschia/or/da/v1/query.proto
> +}
```suggestion
}

```

2023-05-18 03:27 UTC, ulbqb commented on proto/finschia/or/da/v1/tx.proto
> +message MsgRemoveSCCBatchResponse {}
```suggestion
message MsgRemoveSCCBatchResponse {}

```

2023-05-18 03:27 UTC, ulbqb commented on proto/finschia/or/da/v1/query.proto
> +    option (google.api.http).get = "/checkers/da/batches/cc";
```suggestion
    option (google.api.http).get = "/finschia/or/da/v1/batches/cc";
```

2023-05-18 07:16 UTC, ulbqb approved these changes

2023-05-18 07:17 UTC, merged